getNewData:
	wget -q --no-check-certificate --no-cache --no-cookies --show-progress 'https://opensheet.elk.sh/1JZM_9U7hYtq39T0BeZHaUrJVKSWWNfxLxcZnrJPiHBQ/monster.json' -O './public/monster.json'; \
	wget -q --no-check-certificate --no-cache --no-cookies --show-progress 'https://opensheet.elk.sh/1JZM_9U7hYtq39T0BeZHaUrJVKSWWNfxLxcZnrJPiHBQ/item.json' -O './public/item.json'; \
	wget -q --no-check-certificate --no-cache --no-cookies --show-progress 'https://opensheet.elk.sh/1JZM_9U7hYtq39T0BeZHaUrJVKSWWNfxLxcZnrJPiHBQ/skill.json' -O './public/skill.json'
