export const filtersDef = [
  {
    prop: 'name_zh',
    label: 'name_zh',
    type: 'text',
    sort: true,
  },
  {
    prop: 'name',
    label: 'name_en',
    type: 'text',
    sort: true,
  },
  {
    prop: 'tier',
    label: 'Tier ★',
    type: 'number',
    list: 'tiers',
    min: 1,
    max: 10,
    sort: true,
  },
  {
    prop: 'equipped_by',
    label: '穿戴者',
    type: 'text',
    list: 'equipped_by',
  },
  {
    prop: 'type',
    label: '裝備類型',
    type: 'text',
    list: 'types',
    // exact: true,
    sort: true,
  },
  {
    prop: 'prevents',
    label: '-免疫(敵)',
    type: 'text',
    list: 'prevents',
  },
  {
    prop: 'cures',
    label: '-治癒(己)',
    type: 'text',
    list: 'cures',
  },
  {
    prop: 'causes',
    label: '+造成(敵)',
    type: 'text',
    list: 'causes',
  },
  {
    prop: 'gives',
    label: '+給予(己)',
    type: 'text',
    list: 'gives',
  },
  {
    prop: 'element',
    label: '元素',
    type: 'text',
    list: 'element',
    sort: true,
  },
  {
    prop: 'slots',
    label: '鑲嵌孔數',
    type: 'number',
    sort: true,
  },
  {
    prop: 'boss',
    label: '👿 BOSS',
    type: 'checkbox',
  },
  {
    prop: 'arena',
    label: '🏟️ 競技場',
    type: 'checkbox',
  },
  {
    prop: 'view_distance',
    label: '👁️ +視野',
    type: 'checkbox',
  },
  // {
  //   prop: 'image',
  //   type: 'text',
  // },
  // {
  //   prop: 'stats',
  // },
  {
    prop: 'materials',
    label: '材料id',
    type: 'number',
    checkId: true,
  },
  {
    prop: 'dropped_by',
    label: '掉落者id',
    type: 'number',
    checkId: true,
  },
  // {
  //   prop: 'quests',
  // },
  {
    prop: 'stats.attack',
    label: '.物攻',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.magic',
    label: '.魔攻',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.defense',
    label: '.物防',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.resistance',
    label: '.魔防',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.dexterity',
    label: '.敏捷',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.crit',
    label: '.暴擊',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.ward',
    label: '.護盾',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.mana',
    label: '.魔力',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.hp',
    label: '.血量',
    type: 'number',
    sort: true,
  },
  {
    prop: 'context',
    label: '全文搜索',
    type: 'text',
  },
  // {
  //   prop: 'description',
  //   label: '描述 (en)',
  //   type: 'text',
  // },
  {
    prop: 'id',
    label: 'id',
    type: 'number',
    min: 1,
    sort: true,
  },
];
