export const filtersDef = [
  {
    prop: 'name.zh',
    label: 'name.zh',
    type: 'text',
    sort: true,
  },
  {
    prop: 'name.en',
    label: 'name.en',
    type: 'text',
    sort: true,
  },
  {
    prop: 'tier',
    label: 'Tier ★',
    type: 'number',
    list: 'tiers',
    min: 1,
    max: 10,
    sort: true,
  },
  {
    prop: 'equipped_by',
    label: '穿戴者',
    type: 'text',
    list: 'equipped_by',
  },
  {
    prop: 'type',
    label: '裝備類型',
    type: 'text',
    list: 'types',
    // exact: true,
    sort: true,
  },
  {
    prop: 'category',
    label: '類別',
    type: 'text',
    list: 'categories',
  },
  {
    prop: 'immunities',
    label: '-免疫(敵)',
    type: 'text',
    list: 'immunities',
  },
  {
    prop: 'cures',
    label: '-治療(己)',
    type: 'text',
    list: 'cures',
  },
  {
    prop: 'causes',
    label: '+造成(敵)',
    type: 'text',
    list: 'causes',
  },
  {
    prop: 'gives',
    label: '+賦予(己)',
    type: 'text',
    list: 'gives',
  },
  {
    prop: 'slots',
    label: '槽位數',
    type: 'number',
    sort: true,
  },
  {
    prop: 'two_handed',
    label: '雙手使用',
    type: 'checkbox',
  },
  {
    prop: 'element',
    label: '元素',
    type: 'text',
    list: 'element',
    sort: true,
  },
  {
    prop: 'rarity',
    label: '稀有度',
    type: 'text',
    list: 'rarity',
  },
  {
    prop: 'tags',
    label: 'Tags',
    type: 'text',
    list: 'tags',
  },
  {
    prop: 'boss',
    label: '👿 BOSS',
    type: 'checkbox',
  },
  {
    prop: 'arena',
    label: '🏟️ 競技場',
    type: 'checkbox',
  },
  {
    prop: 'view_distance',
    label: '👁️ +視野',
    type: 'checkbox',
  },
  // {
  //   prop: 'image',
  //   type: 'text',
  // },
  // {
  //   prop: 'stats',
  // },
  {
    prop: 'materials',
    label: '材料id',
    type: 'number',
    checkId: true,
  },
  {
    prop: 'dropped_by',
    label: '掉落者id',
    type: 'number',
    checkId: true,
  },
  // {
  //   prop: 'quests',
  // },
  {
    prop: 'stats.attack',
    label: '.物攻',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.magic',
    label: '.魔攻',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.defense',
    label: '.物防',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.resistance',
    label: '.魔防',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.dexterity',
    label: '.敏捷',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.crit',
    label: '.暴擊',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.ward',
    label: '.護盾',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.mana',
    label: '.魔力',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.hp',
    label: '.血量',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.foresight',
    label: '.預知',
    type: 'number',
    sort: true,
  },
  {
    prop: 'other_effect',
    label: '加成/技能',
    type: 'text',
  },
  {
    prop: 'context',
    label: '全文搜索',
    type: 'text',
  },
  // {
  //   prop: 'description',
  //   label: '描述 (en)',
  //   type: 'text',
  // },
  {
    prop: 'gid',
    label: 'gid',
    type: 'number',
    min: 1,
    sort: true,
  },
];
