export const filtersDef = [
  {
    prop: 'name_zh',
    label: 'name_zh',
    type: 'text',
    sort: true,
  },
  {
    prop: 'name',
    label: 'name_en',
    type: 'text',
    sort: true,
  },
  {
    prop: 'tier',
    label: 'Tier ★',
    type: 'number',
    list: 'tiers',
    min: 1,
    max: 10,
    sort: true,
  },
  {
    prop: 'equipped_by',
    label: '穿戴者',
    type: 'text',
    list: 'equipped_by',
  },
  {
    prop: 'prevents',
    label: '免疫',
    type: 'text',
    list: 'prevents',
  },
  {
    prop: 'causes',
    label: '造成',
    type: 'text',
    list: 'causes',
  },
  {
    prop: 'type',
    label: '裝備位置',
    type: 'text',
    list: 'types',
    // exact: true,
    sort: true,
  },
  {
    prop: 'element',
    label: '元素',
    type: 'text',
    list: 'element',
    sort: true,
  },
  {
    prop: 'boss',
    label: '👿 BOSS',
    type: 'checkbox',
  },
  {
    prop: 'arena',
    label: '🏟️ 競技場',
    type: 'checkbox',
  },
  {
    prop: 'view_distance',
    label: '👁️ +視野',
    type: 'checkbox',
  },
  // {
  //   prop: 'image',
  //   type: 'text',
  // },
  // {
  //   prop: 'stats',
  // },
  // {
  //   prop: 'materials',
  // },
  // {
  //   prop: 'dropped_by',
  // },
  // {
  //   prop: 'quests',
  // },
  {
    prop: 'stats.attack.base',
    label: '.物攻',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.magic.base',
    label: '.魔攻',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.defense.base',
    label: '.物防',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.resistance.base',
    label: '.魔防',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.dexterity.base',
    label: '.敏捷',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.crit.base',
    label: '.暴擊',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.ward.base',
    label: '.護盾',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.mana.base',
    label: '.魔力',
    type: 'number',
    sort: true,
  },
  {
    prop: 'stats.hp.base',
    label: '.血量',
    type: 'number',
    sort: true,
  },
  {
    prop: 'context',
    label: '全文搜索',
    type: 'text',
  },
  {
    prop: 'description',
    label: '描述 (en)',
    type: 'text',
  },
  {
    prop: 'id',
    label: 'id',
    type: 'number',
    min: 1,
    sort: true,
  },
];
